In [17]:
import pandas as pd
import numpy as np

In [18]:
data = pd.read_csv('../datasets/employee.csv')

In [19]:
data

name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [20]:
# Fill missing values with mean
data['age'] = data['age'].fillna(data.age.mean())
data

name        age   income gender  department grade  \
0    Allen Smith  45.000000      NaN    NaN  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0    NaN       Sales    G3   
6   James Authur  54.000000      NaN      F  Operations    G3   
7     Josh Wills  54.000000  52000.0      F     Finance    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  
0                723  
1                520  
2                674  
3                556  
4                711  
5                649  
6                 53  
7                901  
8                709

In [21]:
# Fill missing values in income column with median
data['income'] = data['income'].fillna(data.income.median())
data

name        age   income gender  department grade  \
0    Allen Smith  45.000000  52000.0    NaN  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0    NaN       Sales    G3   
6   James Authur  54.000000  52000.0      F  Operations    G3   
7     Josh Wills  54.000000  52000.0      F     Finance    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  
0                723  
1                520  
2                674  
3                556  
4                711  
5                649  
6                 53  
7                901  
8                709

In [28]:
# Fill missing gender values with mode
data['gender']=data['gender'].fillna(data['gender'].mode()[0])
data

name        age   income gender  department grade  \
0    Allen Smith  45.000000  52000.0      F  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0      F       Sales    G3   
6   James Authur  54.000000  52000.0      F  Operations    G3   
7     Josh Wills  54.000000  52000.0      F     Finance    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  
0                723  
1                520  
2                674  
3                556  
4                711  
5                649  
6                 53  
7                901  
8                709

In [29]:
# Handling outliers

In [32]:
# Dropping outliers using standard deviation and mean
upper_limit = data['performance_score'].mean() + 2*data['performance_score'].std()
lower_limit = data['performance_score'].mean() - 2*data['performance_score'].std()

new_data = data[(data['performance_score'] < upper_limit) & (data['performance_score'] > lower_limit)]
new_data

name        age   income gender  department grade  \
0    Allen Smith  45.000000  52000.0      F  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0      F       Sales    G3   
7     Josh Wills  54.000000  52000.0      F     Finance    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  
0                723  
1                520  
2                674  
3                556  
4                711  
5                649  
7                901  
8                709

In [33]:
# Dropping outliers using Percentiles
upper_limit = data['performance_score'].quantile(.99)
lower_limit = data['performance_score'].quantile(.01)
new_data = data[(data['performance_score'] < upper_limit) & (data['performance_score'] > lower_limit)]
new_data

name        age   income gender  department grade  \
0    Allen Smith  45.000000  52000.0      F  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0      F       Sales    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  
0                723  
1                520  
2                674  
3                556  
4                711  
5                649  
8                709

In [34]:
# Feature Encoding Techniques

In [35]:
# one-hot encoding
encoded_data = pd.get_dummies(data['gender'])
encoded_data = data.join(encoded_data)
encoded_data

name        age   income gender  department grade  \
0    Allen Smith  45.000000  52000.0      F  Operations    G3   
1        S Kumar  40.428571  16000.0      F     Finance    G0   
2    Jack Morgan  32.000000  35000.0      M     Finance    G2   
3      Ying Chin  45.000000  65000.0      F       Sales    G3   
4  Dheeraj Patel  30.000000  42000.0      F  Operations    G2   
5  Satyam Sharma  40.428571  62000.0      F       Sales    G3   
6   James Authur  54.000000  52000.0      F  Operations    G3   
7     Josh Wills  54.000000  52000.0      F     Finance    G3   
8       Leo Duck  23.000000  98000.0      M       Sales    G4   

   performance_score  F  M  
0                723  1  0  
1                520  1  0  
2                674  0  1  
3                556  1  0  
4                711  1  0  
5                649  1  0  
6                 53  1  0  
7                901  1  0  
8                709  0  1

In [38]:
# One-hot encoding
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()

onehotencoder.fit_transform(data[['gender']]).toarray()

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [40]:
# Label encoding
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

encoded_data = label_encoder.fit_transform(data['department'])

encoded_data

array([1, 0, 0, 2, 1, 2, 1, 0, 2])

In [42]:
# Inverting labels
decode_label = label_encoder.inverse_transform(encoded_data)
decode_label

array(['Operations', 'Finance', 'Finance', 'Sales', 'Operations', 'Sales',
       'Operations', 'Finance', 'Sales'], dtype=object)

In [46]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=['G0', 'G1', 'G2', 'G3', 'G4'])
encoded_data = label_encoder.fit_transform(data['grade'])
print(encoded_data,'\n',data['grade'])

[2 0 1 2 1 2 2 2 3] 
 0    G3
1    G0
2    G2
3    G3
4    G2
5    G3
6    G3
7    G3
8    G4
Name: grade, dtype: object
